project:
  type: website

website:
  title: "Lukman Adeboye Soboyejo"
  site-url: "https://beamilz.com/"
  google-analytics: "G-2J79YYG9CZ"
  page-footer:
    left: "Blog made with 💜 and [Quarto](https://quarto.org/), by Lukman Adeboye Soboyejo. License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
navbar:
    right:
      - about.qmd
      - text: Posts
      - text: Resume
        href: https://github.com/lukeng200/lukeng200.github.io/blob/master/CV.pdf
      - icon: github
        href: https://github.com/lukeng200
      - icon: twitter
        href: https://twitter.com/Hadeboye
format:
  html:
    smooth-scroll: true
    theme: journal
    css: styles.css
    link-external-icon: false
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/www\.lukman-academic-hub\.netlify.app\/**'
    citations-hover: true
    footnotes-hover: true
    include-in-header: meta.html
    toc: true
    code-link: true
    
comments:
  giscus:
    repo: lukeng200/Lukman_Academic_Hub

editor: visual



