project:
  type: website

website:
  title: "Academic Hub"
navbar:
    right:
      - about.qmd
      - text: Posts
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com/Hadeboye
format:
  html:
    smooth-scroll: true
    theme: journal
    css: styles.css
    link-external-icon: false
    link-external-newwindow: true
    link-external-filter: ''
    citations-hover: true
    footnotes-hover: true
    include-in-header: meta.html
    toc: true
    code-link: true
    
comments:
  giscus:
    repo: lukeng200/Lukman_Academic_Hub

editor: visual



