project:
  type: website

website:
  title: "Academic Hub"
  site-url: "https://lukeng200.com"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    smooth-scroll: true
    theme: tango
    css: styles.css
    
    
comments:
  giscus:
    repo: lukeng200/Lukman_Academic_Hub

editor: visual



