project:
  type: website

website:
  title: "Lukman Adeboye Soboyejo"
  site-url: "https://lukman-academic-hub.netlify.app/"
  page-footer:
    left: "Blog made with 💜, [Netlify](https://www.netlify.com/), and [Quarto](https://quarto.org/), by Lucas. License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
    right:
      - icon: github
        href: https://github.com/lukeng200
      - icon: twitter
        href: https://twitter.com/Hadeboye
      - icon: envelope
        href: lsoboyejo@student.unimelb.edu.au
  twitter-card:
    creator: "@Hadeboye"
    card-style: summary_large_image

# site navigation
  navbar:
    right:
      - about.qmd
      - text: News
        menu:
        - text: All post
          href: news/index.qmd
      - text: Publications
        href: publications/index.qmd
      - text: Software
        href: software/index.qmd
      - text: Conferences / Talks
        href: talks/index.qmd
      - text: Resume
        href: resume/index.qmd
        

    
date-format: "D MMMM YYYY"

format:
  html:
    smooth-scroll: true
    theme: slate
    css: styles.css
    link-external-icon: false
    link-external-newwindow: true
    link-external-filter: ''
    citations-hover: true
    footnotes-hover: true
    include-in-header: meta.html
    toc: true
    code-link: true
    

comments: 
  giscus:
    repo: lukeng200/Lukman_Academic_Hub

editor: visual



